### ISSUE TITLE
step3

### ISSUE THREAD

**Issue by sunynping** [ucsd-ccbb/NetColoc#17]
* netcoloc version:
* Python version:
* Operating System:

### Description
Can I input a network myself，instead of using  STRING？？？

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by coleslaw481** [comment]
Yes you can use any network in CX format that has gene symbols for node names (basically should look similar to PCNet or String high confidence). 

In the example notebooks in "Select gene interaction network to use for the analysis" you'll see PCNet as a commented out option
